package vn.containergo.domain.enumeration;

/**
 * The ContainerState enumeration.
 */
public enum ContainerState {
    NEW,
    BIDDING,
    RECEIVED_OFFERS,
    CONTAINER_CANCEL,
    BIDDING_TIMEUP_WITH_NO_OFFER,
    BIDDING_PENDING,
    OFFER_CHOSEN,
    SHIPMENT_PLAN_SENT,
    OFFER_CANCEL_BY_SHIPPER,
    SHIPMENT_IN_PROGRESS,
    PICKUP_SUCCESS,
    PICKUP_FAILED,
    PICKUP_CANCEL,
    DELIVERY_SUCCESS,
    POD_SUCCESS,
    POD_APPROVED,
    DELIVERY_FAILED,
    WAIT_FOR_CENTER_HANDLE_CONTAINER,
    REDELIVERY,
    RETURNING,
    RETURN_SUCCESS,
    RETURN_FAIL,
    BIDDING_TIMEUP_WITH_OFFER,
    SHIPMENT_SUCCESS,
}
