package vn.containergo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarrierAccountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarrierAccountAllPropertiesEquals(CarrierAccount expected, CarrierAccount actual) {
        assertCarrierAccountAutoGeneratedPropertiesEquals(expected, actual);
        assertCarrierAccountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarrierAccountAllUpdatablePropertiesEquals(CarrierAccount expected, CarrierAccount actual) {
        assertCarrierAccountUpdatableFieldsEquals(expected, actual);
        assertCarrierAccountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarrierAccountAutoGeneratedPropertiesEquals(CarrierAccount expected, CarrierAccount actual) {
        assertThat(expected)
            .as("Verify CarrierAccount auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarrierAccountUpdatableFieldsEquals(CarrierAccount expected, CarrierAccount actual) {
        assertThat(expected)
            .as("Verify CarrierAccount relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarrierAccountUpdatableRelationshipsEquals(CarrierAccount expected, CarrierAccount actual) {
        assertThat(expected)
            .as("Verify CarrierAccount relationships")
            .satisfies(e -> assertThat(e.getCarrier()).as("check carrier").isEqualTo(actual.getCarrier()));
    }
}
