package vn.containergo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CenterPersonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonAllPropertiesEquals(CenterPerson expected, CenterPerson actual) {
        assertCenterPersonAutoGeneratedPropertiesEquals(expected, actual);
        assertCenterPersonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonAllUpdatablePropertiesEquals(CenterPerson expected, CenterPerson actual) {
        assertCenterPersonUpdatableFieldsEquals(expected, actual);
        assertCenterPersonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonAutoGeneratedPropertiesEquals(CenterPerson expected, CenterPerson actual) {
        assertThat(expected)
            .as("Verify CenterPerson auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonUpdatableFieldsEquals(CenterPerson expected, CenterPerson actual) {
        assertThat(expected)
            .as("Verify CenterPerson relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonUpdatableRelationshipsEquals(CenterPerson expected, CenterPerson actual) {
        assertThat(expected)
            .as("Verify CenterPerson relationships")
            .satisfies(e -> assertThat(e.getGroups()).as("check groups").isEqualTo(actual.getGroups()));
    }
}
