package vn.containergo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CenterPersonGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonGroupAllPropertiesEquals(CenterPersonGroup expected, CenterPersonGroup actual) {
        assertCenterPersonGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertCenterPersonGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonGroupAllUpdatablePropertiesEquals(CenterPersonGroup expected, CenterPersonGroup actual) {
        assertCenterPersonGroupUpdatableFieldsEquals(expected, actual);
        assertCenterPersonGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonGroupAutoGeneratedPropertiesEquals(CenterPersonGroup expected, CenterPersonGroup actual) {
        assertThat(expected)
            .as("Verify CenterPersonGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonGroupUpdatableFieldsEquals(CenterPersonGroup expected, CenterPersonGroup actual) {
        assertThat(expected)
            .as("Verify CenterPersonGroup relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCenterPersonGroupUpdatableRelationshipsEquals(CenterPersonGroup expected, CenterPersonGroup actual) {}
}
