package vn.containergo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContainerStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContainerStatusAllPropertiesEquals(ContainerStatus expected, ContainerStatus actual) {
        assertContainerStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertContainerStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContainerStatusAllUpdatablePropertiesEquals(ContainerStatus expected, ContainerStatus actual) {
        assertContainerStatusUpdatableFieldsEquals(expected, actual);
        assertContainerStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContainerStatusAutoGeneratedPropertiesEquals(ContainerStatus expected, ContainerStatus actual) {
        assertThat(expected)
            .as("Verify ContainerStatus auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContainerStatusUpdatableFieldsEquals(ContainerStatus expected, ContainerStatus actual) {
        assertThat(expected)
            .as("Verify ContainerStatus relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContainerStatusUpdatableRelationshipsEquals(ContainerStatus expected, ContainerStatus actual) {
        assertThat(expected)
            .as("Verify ContainerStatus relationships")
            .satisfies(e -> assertThat(e.getGroup()).as("check group").isEqualTo(actual.getGroup()));
    }
}
