package vn.containergo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProviceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProviceAllPropertiesEquals(Provice expected, Provice actual) {
        assertProviceAutoGeneratedPropertiesEquals(expected, actual);
        assertProviceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProviceAllUpdatablePropertiesEquals(Provice expected, Provice actual) {
        assertProviceUpdatableFieldsEquals(expected, actual);
        assertProviceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProviceAutoGeneratedPropertiesEquals(Provice expected, Provice actual) {
        assertThat(expected)
            .as("Verify Provice auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProviceUpdatableFieldsEquals(Provice expected, Provice actual) {
        assertThat(expected)
            .as("Verify Provice relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProviceUpdatableRelationshipsEquals(Provice expected, Provice actual) {}
}
